### ISSUE TITLE
Move fetching data from client to server

### ISSUE THREAD

**Issue by julianpulido272** [Los-Camarones/RealEstate#105]
Files in:
`my-app\src\components\ContactMe\ContactMe.tsx`

`my-app\src\app\Aboutme\page.tsx`

fetch data directly on the client, which poses a security risk as API keys and environment variables can be exposed per [Next.js documentation](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching#fetching-data-on-the-client)

TODO:

- [ ] Create server actions in /Actions that fetch data on the server

**Comment by jovdim** [comment]
**Hello,**

I’m interested in working on this, but I have a question regarding the environment variable used for this application. Could you provide some details?

Thank you!

**Comment by julianpulido272** [comment]
The project is not open for outside contribution at the moment
